exports.android = "android";
exports.ios = "ios";
exports.XLIFF_SUFFIX = '.xliff';
exports.XCLOC_SUFFIX = '.xcloc';

exports.androidLanguageToCode = {
    "English": [undefined],
    "Japanese": ["ja"],
    "German": ["de"],
    "French (France)": ["fr"],
    "Spanish (Spain)": ["es"],
    "Simplified Chinese": ["zh"],
    "Italian": ["it"],
    "Dutch": ["nl"],
    "Portuguese (Portugal)": ["pt"],
    "Swedish": ["sv"],
    "Finnish": ["fi"],
    "Norwegian": ["nb-rNO"],
    "Danish": ["da"],
    "Estonian": ["et"],
    "Latvian": ["lv"],
    "Lithuanian": ["lt"],
    "French (Canada)": ["fr-rCA"],
    "Portuguese (Brazil)": ["pt-rBR"],
    "Spanish (Mexico)": ["es-rMX"],
    "Turkish": ["tr-rTR"],
    "Greek": ["el"],
    "Traditional Chinese": ["zh-rHK", "zh-rTW"],
    "Thai": ["th-rTH"],
    "Indonesian (Bahasa Indonesia)": ["id", "in"],
    "Russian": ["ru-rRU"],
    "Polish": ["pl"],
    "Hebrew": ["he", "iw"],
    "Hungarian": ["hu"],
    "Slovakian": ["sk"],
    "Czech": ["cs"],
    "Arabic": ["ar"]
};

exports.iosLanguageToCode = {
    "English": ["en","en-CA", "en-GB"],
    "Japanese": ["ja", "ja-JP"],
    "German": ["de","de-DE"],
    "French (France)": ["fr","fr-FR"],
    "Spanish (Spain)": ["es","es-ES"],
    "Italian": ["it", "it-IT"],
    "Dutch": ["nl", "nl-NL"],
    "Portuguese (Portugal)": ["pt-PT"],
    "Swedish": ["sv", "sv-SE"],
    "Finnish": ["fi", "fi-FI"],
    "Norwegian": ["nb","nb-NO"],
    "Danish": ["da","da-DK"],
    "Estonian": ["et", "et-EE"],
    "Latvian": ["lv", "lv-LV"],
    "Lithuanian": ["lt", "lt-LT"],
    "French (Canada)": ["fr-CA"],
    "Portuguese (Brazil)": ["pt","pt-BR"],
    "Spanish (Mexico)": ["es-MX"],
    "Turkish": ["tr","tr-TR"],
    "Greek": ["el","el-GR"],
    "Simplified Chinese": ["zh","zh-CN","zh-Hans"],
    "Traditional Chinese": ["zh-Hant","zh-TW","zh-HK"],
    "Thai": ["th","th-TH"],
    "Indonesian (Bahasa Indonesia)": ["id", "id-ID"],
    "Russian": ["ru","ru-RU"],
    "Polish": ["pl","pl-PL"],
    "Hebrew": ["he", "he-IL"],
    "Hungarian": ["hu", "hu-HU"],
    "Slovakian": ["sk","sk-SK"],
    "Czech": ["cs","cs-CZ"],
    "Arabic": ["ar"]
};