exports.android = "android";
exports.ios = "ios";
exports.XLIFF_SUFFIX = '.xliff';
exports.XCLOC_SUFFIX = '.xcloc';

exports.androidLanguageToCode = {
    "English": [undefined],
    "Japanese": ["ja"],
    "German": ["de"],
    "French (France)": ["fr"],
    "Spanish (Spain)": ["es"],
    "Simplified Chinese": ["zh"],
    "Italian": ["it"],
    "Dutch": ["nl"],
    "Portuguese (Portugal)": ["pt"],
    "Swedish": ["sv"],
    "Finnish": ["fi"],
    "Norwegian": ["nb-rNO"],
    "Danish": ["da"],
    "Estonian": ["et"],
    "Latvian": ["lv"],
    "Lithuanian": ["lt"],
    "French (Canada)": ["fr-rCA"],
    "Portuguese (Brazil)": ["pt-rBR"],
    "Spanish (Mexico)": ["es-rMX"],
    "Turkish": ["tr-rTR"],
    "Greek": ["el"],
    "Traditional Chinese": ["zh-rHK", "zh-rTW"],
    "Thai": ["th-rTH"],
    "Indonesian (Bahasa Indonesia)": ["id", "in"],
    "Russian": ["ru-rRU"],
    "Polish": ["pl"],
    "Hebrew": ["he", "iw"],
    "Hungarian": ["hu"],
    "Slovakian": ["sk"],
    "Czech": ["cs"],
    "Arabic": ["ar"]
};

exports.iosLanguageToCode = {
    "English": ["en"],
    "Japanese": ["ja"],
    "German": ["de"],
    "French (France)": ["fr"],
    "Spanish (Spain)": ["es"],
    "Simplified Chinese": ["zh-Hans"],
    "Italian": ["it"],
    "Dutch": ["nl"],
    "Portuguese (Portugal)": ["pt"],
    "Swedish": ["sv"],
    "Finnish": ["fi"],
    "Norwegian": ["nb-NO"],
    "Danish": ["da"],
    "Estonian": ["et"],
    "Latvian": ["lv"],
    "Lithuanian": ["lt"],
    "French (Canada)": ["fr-CA"],
    "Portuguese (Brazil)": ["pt-BR"],
    "Spanish (Mexico)": ["es-MX"],
    "Turkish": ["tr-TR"],
    "Greek": ["el"],
    "Traditional Chinese": ["zh-Hant"],
    "Thai": ["th-TH"],
    "Indonesian (Bahasa Indonesia)": ["id"],
    "Russian": ["ru-RU"],
    "Polish": ["pl"],
    "Hebrew": ["he"],
    "Hungarian": ["hu"],
    "Slovakian": ["sk"],
    "Czech": ["cs"],
    "Arabic": ["ar"]
};